# Generated by Django 2.2.1 on 2019-05-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('marketplace', models.CharField(max_length=255)),
                ('idFlux', models.PositiveIntegerField()),
                ('order_id', models.CharField(max_length=19, primary_key=True, serialize=False)),
                ('order_mrid', models.CharField(max_length=19)),
                ('order_refid', models.CharField(max_length=19)),
                ('order_purchase_date', models.DateField(default=None, null=True)),
                ('order_purchase_heure', models.TimeField(default=None, null=True)),
                ('order_amount', models.FloatField()),
                ('order_currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingInformations',
            fields=[
                ('tracking_shipped_date', models.DateTimeField(default=None, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.Order')),
            ],
        ),
    ]
